version: "3"

services:
  app:
    build:
      context: .

    ports:
      - "8000:8000" #8000 port on our host to 8000 in 8000 in image
    volumes:        # So that whenever we make some changes,add file in our current app outside it will see  that and update in Docker Image
      - ./app:/app
      #sh -c means -> shell run this command and "0.0.0.0:8000" means run on all ip address available on docker image and map to port 8000 on our local machine
    command: >
     sh -c "python manage.py wait_for_db && 
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000" 
    environment:
      - DB_HOST = db 
      - DB_NAME = app
      - DB_USER = postgres
      - DB_PASS = Testing@123
      # Our database should be available before this service starts
    depends_on:
      - db



  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB   = app
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = Testing@123